# Generated by Django 4.1.4 on 2022-12-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('art', models.IntegerField(unique=True, verbose_name='art')),
                ('status', models.CharField(choices=[('1', 'В наличии'), ('2', 'Под заказ'), ('3', 'Ожидается поступление'), ('4', 'Нет в наличии'), ('5', 'Не производится')], max_length=255, verbose_name='status')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='images/product/', verbose_name='path')),
                ('formats', models.CharField(max_length=255, verbose_name='formats')),
                ('prod_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='image', to='tstshop.product')),
            ],
            options={
                'verbose_name': 'image',
            },
        ),
    ]
